# Generated by Django 4.1.2 on 2022-12-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Не опубликован'), ('pulished', 'Опубликован')], default='draft', max_length=20, verbose_name='Статус публикации'),
        ),
    ]
