# Generated by Django 4.1.2 on 2022-12-19 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название поделки')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish', verbose_name='URL')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('body', models.TextField(verbose_name='Описание поделки')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время публикации')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время занесения на сайт')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('status', models.CharField(choices=[('draft', 'Не опубликован'), ('bulished', 'Опубликован')], default='draft', max_length=10, verbose_name='Статус публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блог Творчества',
                'verbose_name_plural': 'Блог Творчеств',
                'ordering': ('-created',),
            },
        ),
    ]
